
--changeset vladB:1
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.columns WHERE table_name='users'
CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    chat_id bigint,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

--changeset vladB:2
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.columns WHERE table_name='workouts'
CREATE TABLE IF NOT EXISTS public.workouts
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone,
    name character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp without time zone,
    user_id bigint,
    CONSTRAINT workouts_pkey PRIMARY KEY (id),
    CONSTRAINT fkpf8ql3wbw2drijbk1ugfvki3d FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

--changeset vladB:3
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.columns WHERE table_name='workouts'
CREATE TABLE IF NOT EXISTS public.exercises
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone,
    type integer,
    updated_at timestamp without time zone,
    workout_id bigint,
    CONSTRAINT exercises_pkey PRIMARY KEY (id),
    CONSTRAINT fk3dr0elb30wvc59xnqo67l38dd FOREIGN KEY (workout_id)
        REFERENCES public.workouts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

--changeset vladB:4
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.columns WHERE table_name='training'
CREATE TABLE IF NOT EXISTS public.training
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone,
    end_time timestamp without time zone,
    start_time timestamp without time zone,
    status integer,
    updated_at timestamp without time zone,
    user_id bigint,
    workout_id bigint,
    CONSTRAINT training_pkey PRIMARY KEY (id),
    CONSTRAINT fk2b2ilx2la6vd45l4tpqmtnlka FOREIGN KEY (workout_id)
        REFERENCES public.workouts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkb1yxuxlhijjfrhlq4ib6g31os FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

--changeset vladB:5
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.columns WHERE table_name='default_activities'
CREATE TABLE IF NOT EXISTS public.default_activities
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone,
    rep integer,
    updated_at timestamp without time zone,
    weight integer,
    exercise_id bigint,
    training_id bigint,
    CONSTRAINT default_activities_pkey PRIMARY KEY (id),
    CONSTRAINT fk2taci7fngu7w6whck2bevkwvd FOREIGN KEY (training_id)
        REFERENCES public.training (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk5ennkccdux069r4ie41a7s4mk FOREIGN KEY (exercise_id)
        REFERENCES public.exercises (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

--changeset vladB:6
ALTER TABLE users ADD bot_state varchar(50) NOT NULL;

